# Generated by Django 5.1.6 on 2025-03-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_quizattempt_quiz_api_qu_user_id_eed165_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_api_qu_user_id_eed165_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_api_qu_categor_f2e13d_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_api_qu_percent_0ce6e3_idx',
        ),
    ]
