# Generated by Django 5.2.3 on 2026-02-14 16:06

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0006_quizsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-created_at'], name='idx_attempt_user_created'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['category'], name='idx_attempt_category'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', '-updated_at'], name='idx_session_user_updated'),
        ),
    ]
